"""add start_date to users

Revision ID: 02e80ec63613
Revises: 3d757e43e47a
Create Date: 2026-01-12 08:07:23.215721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e80ec63613'
down_revision: Union[str, None] = '3d757e43e47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'start_date')
    # ### end Alembic commands ###
